product-landing-page
Nooria150/product-landing-page pull request #1
Opened 2024-05-28 19:47 UTC by Nooria150

2024-05-30 16:21 UTC, ahzamir requested changes
### Hi @Nooria150 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although you have done a great job by implementing some of the requirements, but still you need to work on your code in order to get the final approval.
  - Check the comments bellow for more details.
# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
![image](https://github.com/Nooria150/product-landing-page/assets/96838030/f5ebfe5d-59db-4850-a481-c7a73e8273fc)

✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Product Landing Page and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌Your code is clean
✔️Your project has a professional README.md

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-30 16:21 UTC, ahzamir commented on styles.css
> +}
- **[OPTIONAL]** - Give your Header a Background Color and also a z-index to make it show on other elements.

2024-05-30 16:21 UTC, ahzamir commented on index.html
> +          </ul>
- This code is not aligned correctly remove 2 spaces.

2024-05-30 16:21 UTC, ahzamir commented on index.html
> +  </div>
- I can not see the opening tag for these closing div tags so remove them.

2024-05-30 18:40 UTC, Nooria150 commented
I Implement the feedback. #ahzamir

2024-05-30 21:13 UTC, Nooria150 commented
I implement the feedback. @ahzamir

2024-06-01 09:39 UTC, ahzamir approved these changes
### Hi @Nooria150 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Nooria150/product-landing-page/assets/96838030/f5ebfe5d-59db-4850-a481-c7a73e8273fc)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Product Landing Page project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-04 18:24 UTC, ahzamir commented
@Nooria150 

- Why don't you merge your pull-request after getting the approval?

2024-06-04 20:43 UTC, Nooria150 commented
sorry sir! I wont this mistake.

2024-06-04 20:43 UTC, merged